# Generated by Django 5.0.6 on 2024-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
